[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  
  [functions."stripe-webhook"]
  external_node_modules = ["stripe"]
  included_files = ["functions/stripe-webhook.js"]

[dev]
  # To prevent Netlify dev zpracování těla
  # Tento blok zakáže JSON parsing těla a nechá ho jako raw
  # (Tato možnost není vždy oficiálně dokumentovaná a může se měnit)
  functions = { "stripe-webhook" = { "skip_payload_parsing" = true } }

[build]
  command = "npm install"
  publish = "main"
  functions = "netlify/functions"

[functions."stripe-webhook"]
  external_node_modules = ["stripe"]
  included_files = ["functions/stripe-webhook.js"]

[[headers]]
  for = "/robots.txt"
  [headers.values]
  Content-Type = "text/plain"

[[redirects]]
  from = "http://www.tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true
  
# Přesměrování samotného rootu bez lomítka
[[redirects]]
  from = "http://www.tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true

[[redirects]]
  from = "http://tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true