[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

  # konfigurace pro webhook funkci
  [functions."stripe-webhook"]
  external_node_modules = ["stripe"]
  included_files = ["functions/stripe-webhook.js"]

[dev]
  # pokud funguje, tak toto zakáže JSON parsing pro stripe-webhook
  functions = { "stripe-webhook" = { "skip_payload_parsing" = true } }

[build]
  command = "npm install"
  publish = "main"
  functions = "netlify/functions"

[[headers]]
  for = "/robots.txt"
  [headers.values]
  Content-Type = "text/plain"

[[redirects]]
  from = "http://www.tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true

[[redirects]]
  from = "http://tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true
