[build]
  command = "npm run"
  publish = "main"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"  
  [functions."stripe-webhook"]
    include_files = []
    node_bundler = "esbuild"
    external_node_modules = ["stripe"]

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[headers]]
  for = "/robots.txt"
  [headers.values]
  Content-Type = "text/plain"

[[redirects]]
  from = "http://www.tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://tigry.art/*"
  to = "https://tigry.art/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true

[[redirects]]
  from = "http://tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tigry.art"
  to = "https://tigry.art"
  status = 301
  force = true
